name: Clean Up

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to clean (DEV/QA)'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - QA

permissions:
  id-token: write  # necessary for Azure login

jobs:
  terraform-clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: service_principal

      - name: Terraform Init
        run: terraform init
        
      - name: unlock
        run: terraform force-unlock -force "a94dd210-89f6-294d-8c9e-48cd7e24c97e"
      
      - name: Terraform Destroy
        env:
          TF_VAR_mysubscriptionid: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_mytenantid: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_environment: ${{ github.event.inputs.environment }}
        run: terraform destroy -auto-approve
