name: Clean Up

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to clean (DEV/QA)'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - QA

jobs:
  terraform-clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var="environment=${{ github.event.inputs.environment }}"
