name: Terraform Deployment to Azure
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy (DEV/QA)'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - QA
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="environment=${{ github.event.inputs.environment }}"

      - name: Terraform Apply
        if: ${{ github.event.inputs.environment == 'DEV' || github.event.inputs.environment == 'QA' }}
        run: terraform apply -auto-approve -var="environment=${{ github.event.inputs.environment }}"
