name: Terraform Deployment to Azure
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy (DEV/QA)'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - QA

permissions:
  id-token: write  # necessary for Azure login

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: service_principal

      - name: Create storage for Terraform state in Azure
        run: chmod +x ./Create_storage_for_terraform_state.sh && ./Create_storage_for_terraform_state.sh
      
      - name: Terraform Init
        run: terraform init

      #- name: unlock
      #  run: terraform force-unlock -force "fc798909-97da-bc54-128a-69a4e2f311c9"
      
      - name: Terraform Plan
        env:
          TF_VAR_mysubscriptionid: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_mytenantid: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform plan -var="environment=${{ github.event.inputs.environment }}"

      - name: Terraform Apply
        if: ${{ github.event.inputs.environment == 'DEV' || github.event.inputs.environment == 'QA' }}
        env:
          TF_VAR_mysubscriptionid: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_mytenantid: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform apply -auto-approve -var="environment=${{ github.event.inputs.environment }}" 
